### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/pwa-for-wp#1]
- [x] WEB APP MANIFEST / Service Worker

- [x] Splash Screen

- [x] Homescreen notification and Icon

- [x] Offline Support

- [ ] Push notifications

**Comment by ajeetku** [comment]
- [ ] Update code added? **(Ajeet)**
- [ ] Add in the array of core. [Added array in  #2284]
 

- [ ] Create product and get the slug from backend. **(Ahmed)**


- [ ] Product Page

- [ ] BlogPost + Image


- [ ] Add it in Homepage & Extensions Page

- [ ] Scheduele Email
 
- [ ] Docs
- [ ] Add in the Notice bar
